In [1]:
import numpy as np

Exercise 1

In [2]:
ex1 = np.matrix(np.reshape(np.arange(10,22), (3,4)))
ex1

matrix([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])

Exercise 2

In [3]:
ex2_test_arr = np.random.randint(-10, 10, size = (10))
def has_no_zeros(arr):
    return not 0 in arr

print(ex2_test_arr)
has_no_zeros(ex2_test_arr)

[  3   9   6  -5   1 -10   9   0   9  -9]


False

Exercise 3

In [4]:
from sys import getsizeof
ex3_arr = np.array([1, 7, 13, 105])
print('Total size of elements: {}'.format(ex3_arr.nbytes))
print('Memory occupied by the array object: {}'.format(getsizeof(ex3_arr)))

Total size of elements: 16
Memory occupied by the array object: 112


Exercise 4

In [5]:
ex4 = np.arange(30, 71)
ex4

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

Exercise 5


In [6]:
ex5 = np.array([3,7,4,2])
ex5[::-1]

array([2, 4, 7, 3])

Exercise 6

In [7]:
ex6_arr = np.array([i for i in range(1,100) if i%3 == 0 or i%5 == 0])
print(ex6_arr)
np.sum(ex6_arr)

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]


2318

Exercise 7

In [8]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
print(arrayOne**2)
print(arrayTwo**2)

[[ 25  36  81]
 [441 324 729]]
[[ 225 1089  576]
 [  16   49    1]]


Exercise 8

In [9]:
ex8_arr = np.arange(100, 200, 10)
result = np.reshape(ex8_arr, (5,2))
result

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

Exercise 9

In [10]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(np.max(sampleArray, axis=0))
print(np.min(sampleArray, axis=1))

[82 94 73]
[34 12 53]


Exercise 10

In [11]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

print(arrayOne[:, arrayOne[1].argsort()])
print(arrayTwo[arrayTwo[:,1].argsort(),:])
np.sort(sampleArray)

[[ 6  5  9]
 [18 21 27]]
[[ 4  7  1]
 [15 33 24]]


array([[34, 43, 73],
       [12, 22, 82],
       [53, 66, 94]])